### ISSUE TITLE
How to set action icon?

### ISSUE THREAD

**Issue by JannesStroehlein** [stream-pi/action-api#4]
Hello,

currently I'm writing a plugin for launching steam games. It detects automatically witch games are installed and can launch them. I also found a way to get the icon associated with the game. But if I run the "setIcon(byte[] data)" method, nothing happens.

**Comment by rnayabed** [comment]
Can you elaborate on your issue ? btw `setIcon` doesnt work, i think you want to use `setServerButtonGraphic(byte[])` or `setServerButtonGraphic(String fontawesome5code)`

**Comment by JannesStroehlein** [comment]
I think what I need is a event for when the action's settings are changed so I can set the icon to that of the selected game.

**Comment by rnayabed** [comment]
that is something not currently possible.

**Comment by JannesStroehlein** [comment]
My function to set the icon is as follows:

```
public void setGameIcon(int appID){
        String IconCachePath = this.GetSteamDir() + "\\appcache\\librarycache\\";
        String IconName = appID + "_icon.jpg";

        if (Files.exists(Paths.get(IconCachePath, IconName))){
            try {
                byte[] iconData = Files.readAllBytes(Paths.get(IconCachePath, IconName));
                super.saveServerProperties();
                super.setShowIcon(true);
                super.setServerButtonGraphic(IconCachePath + IconName);
                super.setShowDisplayText(false);
            }
            catch (Exception e){
                e.printStackTrace();
            }
        }
        else
            System.out.println("File doesn't exist");
    }
```

**Comment by rnayabed** [comment]
setting icons arent currenrly supported by the api. itll be added in the future.

this isnt possible because therr arent separate instance of the same NormalAction class created. its just one class for x no of actions. when an action is called, the client properties are passed and `onActionClicked` is called.

**Comment by JannesStroehlein** [comment]
Ok thanks. I hope this will be added soon.

**Comment by rnayabed** [comment]
> Ok thanks. I hope this will be added soon.

setting action icon is now possible. this will be documented later.
