### ISSUE TITLE
Add "masked" property type

### ISSUE THREAD

**Issue by j4ckofalltrades** [stream-pi/action-api#6]
Some plugins usually require a key or secret of some sort and it would be good to have these fields obscured e.g. similar to what you would have in HTML with `<input type="password">`.

**Comment by rnayabed** [comment]
Done.

[server](https://github.com/stream-pi/server/commit/52fb075cb1e7eb24e8a6b11399e98e9b90b1cab6)

[actionapi](https://github.com/stream-pi/actionapi/commit/95bbad7b0a59747abc66a83973e3a0ed3932b770)
